SET SCHEMA 'api';

CREATE TABLE attendee (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cid     TEXT NOT NULL,
    name    TEXT NOT NULL,
    nick    TEXT NULL,
    created TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
GRANT SELECT, INSERT ON attendee TO insert_attendee_user, admin_user, web_anon;

CREATE TRIGGER attendee_news
    AFTER INSERT OR UPDATE ON attendee
    FOR EACH ROW
    EXECUTE PROCEDURE websocket_news();
