FROM postgres:9.6
#pgjwt and pgtap needs postgresql-server-dev-9.6.
RUN apt-get update && apt-get install -y \
        curl \
        git \
        postgresql-server-dev-9.6  \
        sudo \
        make

RUN mkdir -p /setup

# Install pgjwt.
# pgjwt is the JSON Web Token implementation for Postgres.
# You can get it here: https://github.com/michelp/pgjwt
RUN git clone https://github.com/michelp/pgjwt /setup/pgwjt
WORKDIR /setup/pgwjt
RUN make install

# Install pgtap.
# pgtap is the test framework used to test stored procedures
# and other things. Quite useful when everything is based on a sound database.
# You can get it here: https://github.com/theory/pgtap/
#
# We only install the Perl module here. The rest of the installation of pgtap
# is done in docker/init.sh.
RUN cpan TAP::Parser::SourceHandler::pgTAP

RUN rm -rf /setup
