FROM nginx:latest
RUN apt-get update && apt-get install -y curl gnupg2 git make

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install -y yarn nodejs

RUN yarn global add purescript
RUN yarn global add pulp
RUN yarn global add bower

RUN mkdir -p /srv/lemmingpants
ADD ./frontend /srv/lemmingpants
WORKDIR /srv/lemmingpants
RUN bower install --allow-root
RUN make compile
RUN mv /srv/lemmingpants/main.js /usr/share/nginx/html/main.js
ADD ./static/index.html /usr/share/nginx/html/index.html

CMD ["nginx", "-g", "daemon off;"]
