version: '3'
volumes:
  static:
services:
  lemmingpants-frontend:
    image: lemmingpants-frontend:latest
    container_name: lemmingpants-frontend
    depends_on:
      - db
      - ws
      - lemmingpants
    volumes:
      - static:/srv/static/

  # Postgrest
  lemmingpants:
    image: lemmingpants-backend:latest
    container_name: lemmingpants
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: lemmingpants-db:latest
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./init.sql:/init.sql
      - ./pg_tests:/pg_tests
      - ./sql:/sql
    environment:
      POSTGRES_USER: lemmingpants
      POSTGRES_PASSWORD: lemmingpants
      POSTGRES_DB: lemmingpants

  ws:
    image: diogob/postgres-websockets
    container_name: ws
    restart: always
    environment:
      PGWS_DB_URI: postgres://lemmingpants:lemmingpants@db/lemmingpants
      PGWS_JWT_SECRET: "feBU1ykZ4icKs2nKam9l8CD84qhgeOl6QQakrUJBiRTUu4dKTLVoH8o"
    ports:
        - "8000:8000"
    depends_on:
      - lemmingpants
      - db
    volumes:
      - ./docker/websockets.conf:/etc/postgres-websockets.conf
      - static:/static/
