FROM debian:stretch
RUN apt-get update && apt-get install -y \
        postgresql-server-dev-9.6  \
        curl

# Host this on dtek maybe, I had issues getting it from github and so I put it here.
RUN curl https://davebay.net/files/postgrest -o /usr/local/bin/postgrest
RUN chmod +x /usr/local/bin/postgrest

RUN mkdir -p /srv/lemmingpants
ADD ./ /srv/lemmingpants
EXPOSE 3000
CMD /srv/lemmingpants/docker/start.sh
