FROM postgres:10.5
#pgjwt and pgtap needs postgresql-server-dev-10.5.
RUN apt-get update && apt-get install -y \
        curl \
        git \
        postgresql-server-dev-10.5  \
        sudo \
        make

RUN mkdir -p /setup

# Install pgjwt.
# pgjwt is the JSON Web Token implementation for Postgres.
# You can get it here: https://github.com/michelp/pgjwt
RUN git clone https://github.com/michelp/pgjwt /setup/pgwjt
WORKDIR /setup/pgwjt

# Install Haskell Stack.
RUN curl https://get.haskellstack.org/ | sh

# Install postgrest
RUN git clone https://github.com/PostgREST/postgrest.git /setup/postgrest
WORKDIR /setup/postgrest
RUN git checkout v5.1.0
RUN stack install

# Install pgtap.
# pgtap is the test framework used to test stored procedures
# and other things. Quite useful when everything is based on a sound database.
# You can get it here: https://github.com/theory/pgtap/
RUN cpan TAP::Parser::SourceHandler::pgTAP
RUN rm -rf /setup
RUN git clone https://github.com/theory/pgtap/ /pgtap \
  && cd /pgtap \
  && make \
  && make install \
  # This might be a bad idea, consider solving this using
  # by installing as normal user
  && chmod -R 777 /pgtap

# Create the volume needed for running Lemmingpants.
RUN mkdir -p /srv/lemmingpants
ADD ./ /srv/lemmingpants
EXPOSE 3000
CMD /srv/lemmingpants/docker/start.sh
