SET SCHEMA 'model';

-- Auth ---------------------------------------------------------------------

CREATE TABLE role (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE users (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    pwhash   TEXT NOT NULL,
    role_id  INTEGER REFERENCES role NOT NULL
);
CREATE UNIQUE INDEX ON users (lower(username));
